CREATE TABLE tbl_emp(
emp_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
emp_name VARCHAR(255) NOT NULL,
gender CHAR ,
email VARCHAR(255),
dept_id INT(11) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE tbl_dept(
dept_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
dept_name VARCHAR(255) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;
